spring.application.name=payment


spring.mongodb.uri=${MONGODB_URI}
spring.liquibase.enabled=false
app.liquibase.change-log=db/changelog/db.changelog-master.yaml
app.external-api.random-number.base-url=${RANDOM_NUMBER_URL}?
resilience4j.circuitbreaker.instances.randomNumberBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.randomNumberBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.randomNumberBreaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.randomNumberBreaker.permitted-number-of-calls-in-half-open-state=3
